name: Build Android APK from zip nested fixed

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -o tecc_app_flutter_with_ci.zip -d .

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get
        working-directory: tecc_app

      - name: Build release APK
        run: flutter build apk --release
        working-directory: tecc_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: tecc_app/build/app/outputs/flutter-apk/app-release.apk
