name: Build Android APK (Release)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Unzip source
        run: unzip -o tecc_app_flutter_with_ci.zip -d .

      - name: Move project files
        run: mv -f tecc_app/tecc_app/* .

      - name: Update intl dependency
        run: flutter pub add intl:^0.20.2

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Android platform exists
        run: flutter create . --platforms=android

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
